[build]
  publish = "build/"
  # command = "npm test && npm run lint && npm run build-prod"
  command = "npm run build-prod"
  functions = "functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.staging.environment]
  API_URL = "https://bracketclub-staging.herokuapp.com"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 3031