export const GOTO_FIRST = 'MASTERS_GOTO_FIRST';
export const GOTO_LAST = 'MASTERS_GOTO_LAST';
export const GOTO_NEXT = 'MASTERS_GOTO_NEXT';
export const GOTO_PREVIOUS = 'MASTERS_GOTO_PREVIOUS';
export const FETCH_SUCCESS = 'MASTERS_FETCH_SUCCESS';
