export const LOGIN_START = 'ME_LOGIN_START';
export const LOGIN = 'ME_LOGIN';
export const LOGOUT = 'ME_LOGOUT';
export const AUTH_ERROR = 'ME_AUTH_ERROR';

export const FRIENDS_FETCH_SUCCESS = 'FRIENDS_FETCH_SUCCESS';
export const FRIENDS_FETCH_START = 'FRIENDS_FETCH_START';
export const FRIENDS_FETCH_ERROR = 'FRIENDS_FETCH_ERROR';
